# Generated by Django 5.0.2 on 2024-02-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminprofileproxy",
            options={
                "verbose_name": "профиль администратора",
                "verbose_name_plural": "профили администраторов",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmembership",
            options={
                "verbose_name": "участие в проекте",
                "verbose_name_plural": "участия в проектах",
            },
        ),
        migrations.AlterModelOptions(
            name="sociallink",
            options={
                "verbose_name": "социальная ссылка",
                "verbose_name_plural": "социальные ссылки",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-due_date"],
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
            },
        ),
        migrations.AlterModelOptions(
            name="taskcomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "комментарий к задаче",
                "verbose_name_plural": "комментарии к задачам",
            },
        ),
        migrations.AlterModelOptions(
            name="taskmedia",
            options={
                "verbose_name": "медиа для задачи",
                "verbose_name_plural": "медиа для задач",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
            },
        ),
    ]
