# Generated by Django 5.0.2 on 2024-02-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ("first_name", "last_name", "date_joined"),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ("user",),
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
            },
        ),
    ]
