# Generated by Django 5.0.2 on 2024-02-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_adminprofileproxy_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="создатель проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="project_images/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                through="core.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="участники",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
                verbose_name="проект",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("developer", "Developer")],
                max_length=50,
                verbose_name="роль",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="участник",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="link",
            field=models.URLField(verbose_name="ссылка"),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform_name",
            field=models.CharField(
                max_length=255, verbose_name="название социальной сети"
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.userprofile",
                verbose_name="профиль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ответственный",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborating_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="дополнительные сотрудники",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="срок выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=255,
                verbose_name="приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
                verbose_name="проект",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                max_length=255,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.taskcomment",
                verbose_name="родительский комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.task",
                verbose_name="задача",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="taskmedia",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="taskmedia",
            name="file",
            field=models.FileField(
                blank=True, upload_to="task_files/", verbose_name="файл"
            ),
        ),
        migrations.AlterField(
            model_name="taskmedia",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="task_images/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="taskmedia",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.task",
                verbose_name="задача",
            ),
        ),
        migrations.AlterField(
            model_name="taskmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="аватар"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, verbose_name="описание пользователя в профиле (биография)"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="дата рождения"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
    ]
